#!/usr/bin/env python

import os
import sys

os.chdir(os.path.normpath(os.path.join(os.path.abspath(__file__), os.pardir)))

cmd = 'py.test --cov-report term-missing --cov . media_mover/*.py tests/*.py'
rc = os.system(cmd)
sys.exit(rc >> 8)

# EOF
